# NHANES dataset

This Python notebook will read some files of the NHANES dataset.<br>

The NHANES dataset is an American open-source dataset which stands for the National Health And Nutrition Examination Survey.

All data files are stored on the Centers and Disease Control website: https://wwwn.cdc.gov/nchs/nhanes/Default.aspx.<br>
There are data files dating from the year 1999-2026.<br>
The data files are stored in data files from a 2-year time frame.

Each 2-year time frame contains a lot of different variables of almost 10.000 people.<br>
The most important datasets for our problem would be the demographics, blood pressure, glucose and cholesterol.<br>
These datasets can be found at the following:
- Demographics Data &rarr; Demographic Variables & Sample Weights
- Examination Data &rarr; Blood pressure
- Laboratory Data &rarr; Plasma Fasting Glucose & Insulin
- Laboratory Data &rarr; Cholesterol - HDL
- Laboratory Data &rarr; Cholesterol - Total

Each dataset has a representive documentation. This documentation is provided with an explanation about the different variables (column names), and shows us how many datapoints in the dataset belong to each categorical or numerical value, and how many rows are missing.<br>

The data files are saved as *.xpt files, they can be downloaded and read with this script.

## Data files

We first need to read the *.xpt files.<br>
We can read the *.xpt files with pandas and save the CSV files.

The first column of each dataset is the participant ID, so all datasets can be merged with each other.

The notebook below shows the most important variables of each dataset and a preview of how the dataset looks like.

In [3]:
import pandas as pd

### Demographics dataset

- SEQN - Participant ID
- RIAGENDR - Gender (1=male; 2=female)
- RIDAGEYR - Age
- RIDRETH3 - Ethnicity (1=Mexican American, 2=Other Hispanic, 3=Non-Hispanic White, 4=Non-Hispanic Black, 6=Non-Hispanic Asian, 7=Other Race - Including Multi-Racial)

In [ ]:
# Read the NHANES demographics dataset from the XPT file
df_demographics = pd.read_sas("2017-2018/xpt/DEMO_J.XPT", format="xport")
# Save the DataFrame to a readable CSV file
df_demographics.to_csv("2017-2018/csv/DEMO_J.csv", index=False)
df_demographics

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHREDZ,DMDHRMAZ,DMDHSEDZ,WTINT2YR,WTMEC2YR,SDMVPSU,SDMVSTRA,INDHHIN2,INDFMIN2,INDFMPIR
0,93703.0,10.0,2.0,2.0,2.0,NaN,5.0,6.0,2.0,27.0,...,3.0,1.0,3.0,9246.491865,8539.731348,2.0,145.0,15.0,15.0,5.00
1,93704.0,10.0,2.0,1.0,2.0,NaN,3.0,3.0,1.0,33.0,...,3.0,1.0,2.0,37338.768343,42566.614750,1.0,143.0,15.0,15.0,5.00
2,93705.0,10.0,2.0,2.0,66.0,NaN,4.0,4.0,2.0,NaN,...,1.0,2.0,NaN,8614.571172,8338.419786,2.0,145.0,3.0,3.0,0.82
3,93706.0,10.0,2.0,1.0,18.0,NaN,5.0,6.0,2.0,222.0,...,3.0,1.0,2.0,8548.632619,8723.439814,2.0,134.0,NaN,NaN,NaN
4,93707.0,10.0,2.0,1.0,13.0,NaN,5.0,7.0,2.0,158.0,...,2.0,1.0,3.0,6769.344567,7064.609730,1.0,138.0,10.0,10.0,1.88
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9249,102952.0,10.0,2.0,2.0,70.0,NaN,5.0,6.0,2.0,NaN,...,2.0,1.0,1.0,16896.276203,18338.711104,2.0,138.0,4.0,4.0,0.95
9250,102953.0,10.0,2.0,1.0,42.0,NaN,1.0,1.0,2.0,NaN,...,2.0,2.0,NaN,61630.380013,63661.951573,2.0,137.0,12.0,12.0,NaN
9251,102954.0,10.0,2.0,2.0,41.0,NaN,4.0,4.0,1.0,NaN,...,2.0,2.0,NaN,17160.895269,17694.783346,1.0,144.0,10.0,10.0,1.18
9252,102955.0,10.0,2.0,2.0,14.0,NaN,4.0,4.0,2.0,175.0,...,2.0,1.0,2.0,14238.445922,14871.839636,1.0,136.0,9.0,9.0,2.24
9253,102956.0,10.0,2.0,1.0,38.0,NaN,3.0,3.0,2.0,NaN,...,2.0,2.0,NaN,38645.740291,39426.299948,1.0,142.0,7.0,7.0,1.56

### Blood pressure dataset

- SEQN - Participant ID
- BPXCHR - Heart rate
- BPXPLS - Heart pulse
- BPXSY1 - Systolic blood pressure (top number)
- BPXDI1 - Diastolic blood pressure (bottom number)

Blood pressure is measured 4 times.

In [11]:
# Read the NHANES blood pressure dataset from the XPT file
df_blood_pressure = pd.read_sas("2017-2018/xpt/BPX_J.XPT", format="xport")
# Save the DataFrame to a readable CSV file
df_blood_pressure.to_csv("2017-2018/csv/BPX_J.csv", index=False)
df_blood_pressure

,SEQN,PEASCCT1,BPXCHR,BPAARM,BPACSZ,BPXPLS,BPXPULS,BPXPTY,BPXML1,BPXSY1,...,BPAEN1,BPXSY2,BPXDI2,BPAEN2,BPXSY3,BPXDI3,BPAEN3,BPXSY4,BPXDI4,BPAEN4
0,93703.0,NaN,120.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,93704.0,NaN,114.0,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,93705.0,NaN,NaN,1.0,4.0,52.0,1.0,1.0,220.0,NaN,...,NaN,NaN,NaN,NaN,202.0,62.0,2.0,198.0,74.0,2.0
3,93706.0,NaN,NaN,1.0,3.0,82.0,1.0,1.0,140.0,112.0,...,2.0,114.0,70.0,2.0,108.0,76.0,2.0,NaN,NaN,NaN
4,93707.0,NaN,NaN,1.0,2.0,100.0,1.0,1.0,140.0,128.0,...,2.0,128.0,46.0,2.0,128.0,58.0,2.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8699,102952.0,NaN,NaN,1.0,3.0,68.0,1.0,1.0,150.0,136.0,...,2.0,142.0,78.0,2.0,140.0,68.0,2.0,NaN,NaN,NaN
8700,102953.0,NaN,NaN,1.0,5.0,78.0,1.0,1.0,150.0,124.0,...,2.0,122.0,76.0,2.0,116.0,74.0,2.0,NaN,NaN,NaN
8701,102954.0,NaN,NaN,1.0,3.0,78.0,1.0,1.0,150.0,116.0,...,2.0,118.0,72.0,2.0,114.0,74.0,2.0,NaN,NaN,NaN
8702,102955.0,NaN,NaN,1.0,5.0,74.0,1.0,1.0,140.0,114.0,...,2.0,114.0,60.0,2.0,114.0,64.0,2.0,NaN,NaN,NaN
8703,102956.0,NaN,NaN,1.0,5.0,76.0,1.0,1.0,160.0,150.0,...,2.0,146.0,92.0,2.0,148.0,98.0,2.0,NaN,NaN,NaN

### Glucose dataset

- SEQN - Participant ID
- LBXGLU - Fasting Glucose (mg/dL)
- LBDGLUSI - Fasting Glucose (mmol/L)

In [12]:
# Read the NHANES glucose dataset from the XPT file
df_glucose = pd.read_sas("2017-2018/xpt/GLU_J.XPT", format="xport")
# Save the DataFrame to a readable CSV file
df_glucose.to_csv("2017-2018/csv/GLU_J.csv", index=False)
df_glucose

          SEQN      WTSAF2YR  LBXGLU  LBDGLUSI
0      93708.0  2.565368e+04   122.0      6.77
1      93711.0  2.922605e+04   107.0      5.94
2      93717.0  1.371510e+05    91.0      5.05
3      93718.0  5.888331e+04    89.0      4.94
4      93719.0  5.397605e-79    86.0      4.77
...        ...           ...     ...       ...
3031  102947.0  3.208847e+04    85.0      4.72
3032  102948.0  2.911334e+05    92.0      5.11
3033  102952.0  3.273305e+04   158.0      8.77
3034  102954.0  5.063745e+04    94.0      5.22
3035  102956.0  9.233024e+04    91.0      5.05

[3036 rows x 4 columns]

### Total Cholesterol dataset

- SEQN - Participant ID
- LBXTC - Total Cholesterol (mg/dL)
- LBDTCSI - Total Cholesterol (mmol/L)

In [14]:
# Read the NHANES total cholesterol dataset from the XPT file
df_cholesterol = pd.read_sas("2017-2018/xpt/TCHOL_J.XPT", format="xport")
# Save the DataFrame to a readable CSV file
df_cholesterol.to_csv("2017-2018/csv/TCHOL_J.csv", index=False)
df_cholesterol

          SEQN  LBXTC  LBDTCSI
0      93705.0  157.0     4.06
1      93706.0  148.0     3.83
2      93707.0  189.0     4.89
3      93708.0  209.0     5.40
4      93709.0  176.0     4.55
...        ...    ...      ...
7430  102952.0  119.0     3.08
7431  102953.0  182.0     4.71
7432  102954.0  172.0     4.45
7433  102955.0  150.0     3.88
7434  102956.0  163.0     4.22

[7435 rows x 3 columns]

### HDL Cholesterol dataset

- SEQN - Participant ID
- LBDHDD - HDL Cholesterol (mg/dL)
- LBHDDSI - HDL Cholesterol (mmol/L)

In [16]:
# Read the NHANES HDL cholesterol dataset from the XPT file
df_hdl = pd.read_sas("2017-2018/xpt/HDL_J.XPT", format="xport")
# Save the DataFrame to a readable CSV file
df_hdl.to_csv("2017-2018/csv/HDL_J.csv", index=False)
df_hdl

          SEQN  LBDHDD  LBDHDDSI
0      93705.0    60.0      1.55
1      93706.0    47.0      1.22
2      93707.0    68.0      1.76
3      93708.0    88.0      2.28
4      93709.0    65.0      1.68
...        ...     ...       ...
7430  102952.0    60.0      1.55
7431  102953.0    49.0      1.27
7432  102954.0    54.0      1.40
7433  102955.0    34.0      0.88
7434  102956.0    34.0      0.88

[7435 rows x 3 columns]